#!/bin/bash

if [ $# -ne 2 ]; then
	echo $0: usage: ./run containername pipeline_file
	exit 1
fi

docker create --name $1 -v $(pwd):/root/images hmlatapie/gstreamer /root/images/$2
docker cp $2 $1:/root/images/
docker start $1 
